#define DHTPIN 2
#define DHTTYPE DHT22

#define BT_TX 7
#define BT_RX 8

#define IN_MEMORY_DB_SIZE 10

#define MAIN_DELAY_MS 100
#define WEATHER_DATA_SAVE_DELAY_SEC 60
#define SHOW_TIME_DELAY_SEC 1

#define SERIAL_BITRATE 9600
